### ISSUE TITLE
How do I run this programme?

### ISSUE THREAD

**Issue by baikaishiuc** [bytecodealliance/regalloc2#154]
I'm a newbie to rust, and after I clone the code, I run the cargo run directly, and he gives me an error! 
error: a bin target must be available for `cargo run`

What should I do?

**Comment by cfallin** [comment]
regalloc2 is mainly a library: you use it by writing another program that calls the register allocator.

Can you describe what you're trying to do in more detail?

**Comment by baikaishiuc** [comment]
> 

Thanks for the reply, I'm working on a dynary binary translator private project and was thinking of possibly optimising register allocation in the next few months, @amanieu recommended this project so wanted to debug it!

Had it been a library, I would have understood that getting it up and running successfully would have taken some time. I need to learn some rust basics.
