### ISSUE TITLE
Feedback/questions/review on the checker

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/regalloc2#36]
Here are my notes, questions, and suggestions while reading over the `regalloc2`
checker. They are pretty raw, feel free to ask for clarification if anything
doesn't make sense.

----------------------

> The analysis lattice is:
>
> ```plain
>                      Top (V)
>                         |
>                        𝒫(V)   // the Powerset of the set of virtual regs
>                         |
>                 Bottom ( ∅ )     // the empty set
> ```

Doesn't `P(V)` already include the empty set and also a top element (V itself)?
Is this because we have an explicit representation of the universe value that
isn't the actual set `V` but just `universe: true`?

---------------------------

> ```rust
> /// Abstract state for an allocation.
> ///
> /// Equivalent to a set of virtual register names, with the
> /// universe-set as top and empty set as bottom lattice element. The
> /// meet-function is thus set intersection.
> #[derive(Clone, Debug, PartialEq, Eq)]
> struct CheckerValue {
>     /// This value is the "universe set".
>     universe: bool,
>     /// The VRegs that this value is equal to.
>     vregs: FxHashSet<VReg>,
> }
> ```

If `universe == true` then the hash set isn't really ever used, right? If my
understanding is correct, then I think this would be slightly cleaner rewritten
as an `enum`:

```rust
enum CheckerValue {
    Universe,
    VRegs(FxHashSet<VReg>),
}
```

Now, not only are we not distracted by having a hash set accessible when
`universe == true` that could potentially lead to bugs if we forget to check
`universe` and only look at the hash set, but we *can't* be wasting heap space
on the hash set's elements when `universe == true` because of the type
definition.

--------------------------

The top level comment is very nice and helpful.

-----------------------------

> ```rust
> /// State that steps through program points as we scan over the instruction stream.
> #[derive(Clone, Debug, PartialEq, Eq)]
> struct CheckerState {
>     top: bool,
>     allocations: FxHashMap<Allocation, CheckerValue>,
> }
> ```

Similar to `CheckerValue` above, I think this could be better rewritten as:

```rust
enum CheckerState {
    Top,
    Allocations(FxHashMap<Allocation, CheckerValue>),
}
```

-----------------------------

That's it! Everything else looks good to me!

**Comment by fitzgen** [comment]
cc @cfallin

**Comment by cfallin** [comment]
Excellent, thank you @fitzgen for giving the checker a careful review! I've created #37 with updates as you suggested.
