### ISSUE TITLE
Remove support for non-SSA code

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/regalloc2#4]
regalloc2 was initially designed for SSA inputs only (with blockparams rather than the more usual phi-nodes).

In the course of porting Cranelift to use regalloc2, we decided to build a shim in regalloc.rs on top of regalloc2, and to make this work, we added support for non-SSA code. This includes:

- Support for more than one def of a given vreg
- Support for "mod" (modify) operands that read and then write a vreg
- More efficient support for move instructions, which are used heavily by Cranelift to lower phis internally before passing code to regalloc

Once we adapt Cranelift's backends to pass SSA to regalloc2 directly instead of using the regalloc.rs API (which will be a significant effort on its own), we will be able to remove this functionality and simplify the code in various places, mostly in liverange computation and in move-generation. We should verify that we obtain equivalent code quality without the move coalescing in particular.

**Comment by chc4** [comment]
The readme mentions that regalloc2 supports both SSA and non-SSA. Is it still planned to eventually remove non-SSA in the future? If so, adding a warning to the readme so people don't depend on that feature might be good.

**Comment by cfallin** [comment]
Yes, it's still the plan -- with a little more urgency lately as we've realized that there are some performance improvements that would be possible if we accept SSA only (basically, better liverange splitting logic by allowing overlap of liveranges for a VReg). We need to resolve the remaining non-SSA cases in Cranelift first and then we're likely to do this. I'll add a note in the README, thanks!
