### ISSUE TITLE
Remove the need for dedicated, non-allocatable scratch registers per class

### ISSUE THREAD

**Issue by cfallin** [bytecodealliance/regalloc2#45]
Currently, regalloc2 requires the embedder to set aside one register from each class as a dedicated scratch register, and exclude this from the list of allocatable registers.

The scratch register for a given class allows "parallel moves" to work in all cases: when we have a cycle of moves that semantically happen concurrently on an edge (due to arguments to blockparams, aka φ-nodes), we need one more storage space than the cycle length in order to lower into a sequence of individual moves.

However, we could take one of several other strategies:
- We could look at the `PReg` allocation maps at the given location, finding a `PReg` that is not in use and using it as the scratch for this one cyclic move;
- Or, we could *create* a scratch register by temporarily saving a register that doesn't participate in the cycle into a stackslot;
- Or, we could use a stackslot as the temporary (this is the only possibility if the cycle involves all registers in the class).

Some care must be taken to handle stack-to-stack moves (we currently guarantee that we don't generate these by using the scratch register as well, saving it off temporarily in a sort of two-level scheme).

The benefit of this would be the addition of one register per class, reducing register pressure and improving runtime performance.

**Comment by bjorn3** [comment]
xchg would also work on x86, right?

**Comment by cfallin** [comment]
Yep, that's also a valid strategy for the two-register-cycle case (and probably the most optimal). Thanks!
