### ISSUE TITLE
Support branch instructions with operands

### ISSUE THREAD

**Issue by Amanieu** [bytecodealliance/regalloc2#91]
Currently branch instructions that take blockparams (which implies that the target block has multiple predecessors) are not allowed to have any operands. However on many targets a temporary register is needed to synthesize a jump whose target is outside the range of a single instruction.

For example on RISC-V any jump to a target outside a +/- 1MB range requires a `auipc tmp, %hi(target); jr tmp, %lo(target)` instruction sequence. I would like to be able to use an `EarlyDef` with a temporary vreg to tell the register allocator to select a free temporary register for `tmp`. Would it be possible to make this work?

**Comment by cfallin** [comment]
This one's a bit tricky: the issue is the interference of "edge moves" with the uses/defs on the branch instruction. We need to put any moves that set up register state for the destination block prior to the branch itself; so conceptually, the branch sees the target block's register state.

We could require a stricter edge-splitting condition to work around this (currently we require no critical edges, but we do not require every edge to be split). However that would penalize the common case perhaps significantly.

What we do in Cranelift for cases like this that require a temp is to keep a temp register permanently set aside and not allocatable by the regalloc. This mostly comes into play when we need to generate spillslot offsets outside the range of load/store amode immediates.

(For the particular case of branch ranges we have the [MachBuffer](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/machinst/buffer.rs) that generates "branch veneers" in islands between blocks when branches go out of range; something like that may suit your use-case better?)

**Comment by Amanieu** [comment]
> This one's a bit tricky: the issue is the interference of "edge moves" with the uses/defs on the branch instruction. We need to put any moves that set up register state for the destination block prior to the branch itself; so conceptually, the branch sees the target block's register state.
>
> We could require a stricter edge-splitting condition to work around this (currently we require no critical edges, but we do not require every edge to be split). However that would penalize the common case perhaps significantly.

I don't see how we could split the code any more than it already is. This situation happens with code of the form:

```
bb0:
	jump bb2(v0) // bb2 is out of range, need a scratch reg for the jump
bb1:
	jump bb2(v1) // bb2 is out of range, need a scratch reg for the jump
bb2(v2);
	...
```

Conceptually what I want is an unspillable vreg that starts in the jump instruction in bb0/bb1 and ends at the start of bb2. I think it might be possible to make this work, but more thought needs to be put into it.

> What we do in Cranelift for cases like this that require a temp is to keep a temp register permanently set aside and not allocatable by the regalloc. This mostly comes into play when we need to generate spillslot offsets outside the range of load/store amode immediates.

I noticed that since `scratch_regs_by_class` was removed, this scratch register is no longer exposed to regalloc. This feels somewhat inefficient since now regalloc will need to find another scratch register instead of using the dedicated one. Perhaps `scratch_regs_by_class` could be re-introduced but made optional (since we only need it for integer registers)?

> (For the particular case of branch ranges we have the [MachBuffer](https://github.com/bytecodealliance/wasmtime/blob/main/cranelift/codegen/src/machinst/buffer.rs) that generates "branch veneers" in islands between blocks when branches go out of range; something like that may suit your use-case better?)

This doesn't help with the fundamental problem, which is that the branch veneer itself still needs a scratch register. Incidentally, I did consider implementing something similar to MachBuffer but in then end used a system similar to RISC-V [linker relaxation](https://maskray.me/blog/2021-03-14-the-dark-side-of-riscv-linker-relaxation) where I emit a full-length multi-instruction branch during codegen and have the linker shrink it to a shorter instruction sequence later if the target is in range. This makes linking a bit more complicated since shrinking instructions means that all branch & data offsets need to be tracked with relocations, but it produces very good code.

**Comment by cfallin** [comment]
>  don't see how we could split the code any more than it already is. This situation happens with code of the form:
>
> ```
> bb0:
>	jump bb2(v0) // bb2 is out of range, need a scratch reg for the jump
> bb1:
>	jump bb2(v1) // bb2 is out of range, need a scratch reg for the jump
> bb2(v2);
>	...
> ```

Right, I guess "splitting the code more" here would mean introducing edge blocks on both bb0->bb2 and bb1->bb2 with branches that do not have other operands (possibly, e.g., just before `bb2` and thus always in range).

The basic issue remains that it's a really conceptually difficult requirement to shoehorn in: the branch's operand isn't really live for a program point range, unlike all other LRs in the allocator, but somehow "across the jump".

More generally: RA2 is starting to get to a state where the features in the frontend (liverange extraction, constraint rewriting) are causing increasingly bad combinatorial complexity issues. I am very wary of introducing support for features like this that can be handled in other ways (dedicated scratch); it feels far too risky for the marginal payoff. I'm hoping that other efforts (SSA-only input, allowing overlapping LRs) might eventually simplify other bits but let's get there first and then evaluate what we can do.

**Comment by Amanieu** [comment]
Fair enough, I figured it was a difficult problem when I couldn't come up with an obvious solution after thinking about it for a few hours.

If we're going to need a dedicated scratch register anyways, would you consider re-introducing `MachineEnv.scratch_by_class` as an `[Option<PReg>; 2]` so the move resolver can use this register for stack-to-stack moves if it is provided by the embedder?

**Comment by Amanieu** [comment]
Closing since the solution seems to be to just reserve a dedicated scratch register, which can now also be shared with regalloc since #117.

**Comment by Amanieu** [comment]
My understanding is that the scratch register is only used within a parallel move, which is placed either before or after the jump. Since the scratch register is not allocatable, it should never hold a live value across the jump and should therefore be free for use by the jump instruction itself.

**Comment by cfallin** [comment]
Oh, I was thinking of uses/inputs, specifically: one can't use the scratch register to feed a hidden input to a branch. You're right though that if all you need is a temp (as you described in your first comment above! I had lost that) then the scratch register will be fine within the instruction.
